package com.ecobee.plugin.ntc;

import com.intellij.ui.ColorUtil;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class NameThatColor {
    private NameThatColor(){};

    public static String getColorName(String colorHexString) {
        colorHexString = colorHexString.toUpperCase();
        if(colorHexString.length() > 6) {
            String alphaValue = colorHexString.substring(0,2);
            int alpha = Math.round((Integer.valueOf(alphaValue, 16) / 256.0f) * 100f);
            colorHexString = colorHexString.substring(2);
            return getColorName(colorHexString) + ("_alpha_" + alpha);
        }

        ColorHolder colorHolder = new ColorHolder(colorHexString, null);
        if(COLOR_MAP.containsKey(colorHolder.colorHex)){
            return COLOR_MAP.get(colorHolder.colorHex).colorName;
        }

        double df= -1, ndf = 0, ndf1 = 0, ndf2 = 0;
        String closestHex = null;
        Set<String> colorHexes = COLOR_MAP.keySet();
        for (String colorHex : colorHexes) {
            ColorHolder holder = COLOR_MAP.get(colorHex);

            ndf1 = Math.pow(colorHolder.r - holder.r, 2) + Math.pow(colorHolder.g - holder.g, 2) + Math.pow(colorHolder.b - holder.b, 2);
            ndf2 = Math.pow(colorHolder.h - holder.h, 2) + Math.pow(colorHolder.s - holder.s, 2) + Math.pow(colorHolder.l - holder.l, 2);
            ndf = ndf1 + ndf2 * 2;

            if(df < 0 || df > ndf)
            {
                df = ndf;
                closestHex = colorHex;
            }
        }
        if(closestHex != null) {
            return COLOR_MAP.get(closestHex).colorName;
        }
        return "unknown_color";
    }

    private static class ColorHolder {
        String colorHex;
        String colorName;
        Color color;

        int r;
        int g;
        int b;

        float h;
        float s;
        float l;

        ColorHolder(String colorHex, String colorName) {
            if(!colorHex.startsWith("#")) {
                colorHex = "#" + colorHex;
            }
            this.colorHex = colorHex;
            if(colorName != null) {
                colorName = colorName.toLowerCase();
                colorName = colorName.replaceAll("\\s+", "_");
                this.colorName = colorName;
            }
            this.color = ColorUtil.fromHex(this.colorHex);

            this.r = this.color.getRed();
            this.g = this.color.getGreen();
            this.b = this.color.getBlue();

            float[] hsl = Color.RGBtoHSB(this.r, this.g, this.b, null);
            this.h = hsl[0];
            this.s = hsl[1];
            this.l = hsl[2];
        }
    }

    private final static Map<String, String> NAMES = new HashMap<String, String>(){{
        put("000000", "Black");
        put("000080", "Navy Blue");
        put("0000C8", "Dark Blue");
        put("0000FF", "Blue");
        put("000741", "Stratos");
        put("001B1C", "Swamp");
        put("002387", "Resolution Blue");
        put("002900", "Deep Fir");
        put("002E20", "Burnham");
        put("002FA7", "International Klein Blue");
        put("003153", "Prussian Blue");
        put("003366", "Midnight Blue");
        put("003399", "Smalt");
        put("003532", "Deep Teal");
        put("003E40", "Cyprus");
        put("004620", "Kaitoke Green");
        put("0047AB", "Cobalt");
        put("004816", "Crusoe");
        put("004950", "Sherpa Blue");
        put("0056A7", "Endeavour");
        put("00581A", "Camarone");
        put("0066CC", "Science Blue");
        put("0066FF", "Blue Ribbon");
        put("00755E", "Tropical Rain Forest");
        put("0076A3", "Allports");
        put("007BA7", "Deep Cerulean");
        put("007EC7", "Lochmara");
        put("007FFF", "Azure Radiance");
        put("008080", "Teal");
        put("0095B6", "Bondi Blue");
        put("009DC4", "Pacific Blue");
        put("00A693", "Persian Green");
        put("00A86B", "Jade");
        put("00CC99", "Caribbean Green");
        put("00CCCC", "Robin's Egg Blue");
        put("00FF00", "Green");
        put("00FF7F", "Spring Green");
        put("00FFFF", "Cyan");
        put("010D1A", "Blue Charcoal");
        put("011635", "Midnight");
        put("011D13", "Holly");
        put("012731", "Daintree");
        put("01361C", "Cardin Green");
        put("01371A", "County Green");
        put("013E62", "Astronaut Blue");
        put("013F6A", "Regal Blue");
        put("014B43", "Aqua Deep");
        put("015E85", "Orient");
        put("016162", "Blue Stone");
        put("016D39", "Fun Green");
        put("01796F", "Pine Green");
        put("017987", "Blue Lagoon");
        put("01826B", "Deep Sea");
        put("01A368", "Green Haze");
        put("022D15", "English Holly");
        put("02402C", "Sherwood Green");
        put("02478E", "Congress Blue");
        put("024E46", "Evening Sea");
        put("026395", "Bahama Blue");
        put("02866F", "Observatory");
        put("02A4D3", "Cerulean");
        put("03163C", "Tangaroa");
        put("032B52", "Green Vogue");
        put("036A6E", "Mosque");
        put("041004", "Midnight Moss");
        put("041322", "Black Pearl");
        put("042E4C", "Blue Whale");
        put("044022", "Zuccini");
        put("044259", "Teal Blue");
        put("051040", "Deep Cove");
        put("051657", "Gulf Blue");
        put("055989", "Venice Blue");
        put("056F57", "Watercourse");
        put("062A78", "Catalina Blue");
        put("063537", "Tiber");
        put("069B81", "Gossamer");
        put("06A189", "Niagara");
        put("073A50", "Tarawera");
        put("080110", "Jaguar");
        put("081910", "Black Bean");
        put("082567", "Deep Sapphire");
        put("088370", "Elf Green");
        put("08E8DE", "Bright Turquoise");
        put("092256", "Downriver");
        put("09230F", "Palm Green");
        put("09255D", "Madison");
        put("093624", "Bottle Green");
        put("095859", "Deep Sea Green");
        put("097F4B", "Salem");
        put("0A001C", "Black Russian");
        put("0A480D", "Dark Fern");
        put("0A6906", "Japanese Laurel");
        put("0A6F75", "Atoll");
        put("0B0B0B", "Cod Gray");
        put("0B0F08", "Marshland");
        put("0B1107", "Gordons Green");
        put("0B1304", "Black Forest");
        put("0B6207", "San Felix");
        put("0BDA51", "Malachite");
        put("0C0B1D", "Ebony");
        put("0C0D0F", "Woodsmoke");
        put("0C1911", "Racing Green");
        put("0C7A79", "Surfie Green");
        put("0C8990", "Blue Chill");
        put("0D0332", "Black Rock");
        put("0D1117", "Bunker");
        put("0D1C19", "Aztec");
        put("0D2E1C", "Bush");
        put("0E0E18", "Cinder");
        put("0E2A30", "Firefly");
        put("0F2D9E", "Torea Bay");
        put("10121D", "Vulcan");
        put("101405", "Green Waterloo");
        put("105852", "Eden");
        put("110C6C", "Arapawa");
        put("120A8F", "Ultramarine");
        put("123447", "Elephant");
        put("126B40", "Jewel");
        put("130000", "Diesel");
        put("130A06", "Asphalt");
        put("13264D", "Blue Zodiac");
        put("134F19", "Parsley");
        put("140600", "Nero");
        put("1450AA", "Tory Blue");
        put("151F4C", "Bunting");
        put("1560BD", "Denim");
        put("15736B", "Genoa");
        put("161928", "Mirage");
        put("161D10", "Hunter Green");
        put("162A40", "Big Stone");
        put("163222", "Celtic");
        put("16322C", "Timber Green");
        put("163531", "Gable Green");
        put("171F04", "Pine Tree");
        put("175579", "Chathams Blue");
        put("182D09", "Deep Forest Green");
        put("18587A", "Blumine");
        put("19330E", "Palm Leaf");
        put("193751", "Nile Blue");
        put("1959A8", "Fun Blue");
        put("1A1A68", "Lucky Point");
        put("1AB385", "Mountain Meadow");
        put("1B0245", "Tolopea");
        put("1B1035", "Haiti");
        put("1B127B", "Deep Koamaru");
        put("1B1404", "Acadia");
        put("1B2F11", "Seaweed");
        put("1B3162", "Biscay");
        put("1B659D", "Matisse");
        put("1C1208", "Crowshead");
        put("1C1E13", "Rangoon Green");
        put("1C39BB", "Persian Blue");
        put("1C402E", "Everglade");
        put("1C7C7D", "Elm");
        put("1D6142", "Green Pea");
        put("1E0F04", "Creole");
        put("1E1609", "Karaka");
        put("1E1708", "El Paso");
        put("1E385B", "Cello");
        put("1E433C", "Te Papa Green");
        put("1E90FF", "Dodger Blue");
        put("1E9AB0", "Eastern Blue");
        put("1F120F", "Night Rider");
        put("1FC2C2", "Java");
        put("20208D", "Jacksons Purple");
        put("202E54", "Cloud Burst");
        put("204852", "Blue Dianne");
        put("211A0E", "Eternity");
        put("220878", "Deep Blue");
        put("228B22", "Forest Green");
        put("233418", "Mallard");
        put("240A40", "Violet");
        put("240C02", "Kilamanjaro");
        put("242A1D", "Log Cabin");
        put("242E16", "Black Olive");
        put("24500F", "Green House");
        put("251607", "Graphite");
        put("251706", "Cannon Black");
        put("251F4F", "Port Gore");
        put("25272C", "Shark");
        put("25311C", "Green Kelp");
        put("2596D1", "Curious Blue");
        put("260368", "Paua");
        put("26056A", "Paris M");
        put("261105", "Wood Bark");
        put("261414", "Gondola");
        put("262335", "Steel Gray");
        put("26283B", "Ebony Clay");
        put("273A81", "Bay of Many");
        put("27504B", "Plantation");
        put("278A5B", "Eucalyptus");
        put("281E15", "Oil");
        put("283A77", "Astronaut");
        put("286ACD", "Mariner");
        put("290C5E", "Violent Violet");
        put("292130", "Bastille");
        put("292319", "Zeus");
        put("292937", "Charade");
        put("297B9A", "Jelly Bean");
        put("29AB87", "Jungle Green");
        put("2A0359", "Cherry Pie");
        put("2A140E", "Coffee Bean");
        put("2A2630", "Baltic Sea");
        put("2A380B", "Turtle Green");
        put("2A52BE", "Cerulean Blue");
        put("2B0202", "Sepia Black");
        put("2B194F", "Valhalla");
        put("2B3228", "Heavy Metal");
        put("2C0E8C", "Blue Gem");
        put("2C1632", "Revolver");
        put("2C2133", "Bleached Cedar");
        put("2C8C84", "Lochinvar");
        put("2D2510", "Mikado");
        put("2D383A", "Outer Space");
        put("2D569B", "St Tropaz");
        put("2E0329", "Jacaranda");
        put("2E1905", "Jacko Bean");
        put("2E3222", "Rangitoto");
        put("2E3F62", "Rhino");
        put("2E8B57", "Sea Green");
        put("2EBFD4", "Scooter");
        put("2F270E", "Onion");
        put("2F3CB3", "Governor Bay");
        put("2F519E", "Sapphire");
        put("2F5A57", "Spectra");
        put("2F6168", "Casal");
        put("300529", "Melanzane");
        put("301F1E", "Cocoa Brown");
        put("302A0F", "Woodrush");
        put("304B6A", "San Juan");
        put("30D5C8", "Turquoise");
        put("311C17", "Eclipse");
        put("314459", "Pickled Bluewood");
        put("315BA1", "Azure");
        put("31728D", "Calypso");
        put("317D82", "Paradiso");
        put("32127A", "Persian Indigo");
        put("32293A", "Blackcurrant");
        put("323232", "Mine Shaft");
        put("325D52", "Stromboli");
        put("327C14", "Bilbao");
        put("327DA0", "Astral");
        put("33036B", "Christalle");
        put("33292F", "Thunder");
        put("33CC99", "Shamrock");
        put("341515", "Tamarind");
        put("350036", "Mardi Gras");
        put("350E42", "Valentino");
        put("350E57", "Jagger");
        put("353542", "Tuna");
        put("354E8C", "Chambray");
        put("363050", "Martinique");
        put("363534", "Tuatara");
        put("363C0D", "Waiouru");
        put("36747D", "Ming");
        put("368716", "La Palma");
        put("370202", "Chocolate");
        put("371D09", "Clinker");
        put("37290E", "Brown Tumbleweed");
        put("373021", "Birch");
        put("377475", "Oracle");
        put("380474", "Blue Diamond");
        put("381A51", "Grape");
        put("383533", "Dune");
        put("384555", "Oxford Blue");
        put("384910", "Clover");
        put("394851", "Limed Spruce");
        put("396413", "Dell");
        put("3A0020", "Toledo");
        put("3A2010", "Sambuca");
        put("3A2A6A", "Jacarta");
        put("3A686C", "William");
        put("3A6A47", "Killarney");
        put("3AB09E", "Keppel");
        put("3B000B", "Temptress");
        put("3B0910", "Aubergine");
        put("3B1F1F", "Jon");
        put("3B2820", "Treehouse");
        put("3B7A57", "Amazon");
        put("3B91B4", "Boston Blue");
        put("3C0878", "Windsor");
        put("3C1206", "Rebel");
        put("3C1F76", "Meteorite");
        put("3C2005", "Dark Ebony");
        put("3C3910", "Camouflage");
        put("3C4151", "Bright Gray");
        put("3C4443", "Cape Cod");
        put("3C493A", "Lunar Green");
        put("3D0C02", "Bean  ");
        put("3D2B1F", "Bistre");
        put("3D7D52", "Goblin");
        put("3E0480", "Kingfisher Daisy");
        put("3E1C14", "Cedar");
        put("3E2B23", "English Walnut");
        put("3E2C1C", "Black Marlin");
        put("3E3A44", "Ship Gray");
        put("3EABBF", "Pelorous");
        put("3F2109", "Bronze");
        put("3F2500", "Cola");
        put("3F3002", "Madras");
        put("3F307F", "Minsk");
        put("3F4C3A", "Cabbage Pont");
        put("3F583B", "Tom Thumb");
        put("3F5D53", "Mineral Green");
        put("3FC1AA", "Puerto Rico");
        put("3FFF00", "Harlequin");
        put("401801", "Brown Pod");
        put("40291D", "Cork");
        put("403B38", "Masala");
        put("403D19", "Thatch Green");
        put("405169", "Fiord");
        put("40826D", "Viridian");
        put("40A860", "Chateau Green");
        put("410056", "Ripe Plum");
        put("411F10", "Paco");
        put("412010", "Deep Oak");
        put("413C37", "Merlin");
        put("414257", "Gun Powder");
        put("414C7D", "East Bay");
        put("4169E1", "Royal Blue");
        put("41AA78", "Ocean Green");
        put("420303", "Burnt Maroon");
        put("423921", "Lisbon Brown");
        put("427977", "Faded Jade");
        put("431560", "Scarlet Gum");
        put("433120", "Iroko");
        put("433E37", "Armadillo");
        put("434C59", "River Bed");
        put("436A0D", "Green Leaf");
        put("44012D", "Barossa");
        put("441D00", "Morocco Brown");
        put("444954", "Mako");
        put("454936", "Kelp");
        put("456CAC", "San Marino");
        put("45B1E8", "Picton Blue");
        put("460B41", "Loulou");
        put("462425", "Crater Brown");
        put("465945", "Gray Asparagus");
        put("4682B4", "Steel Blue");
        put("480404", "Rustic Red");
        put("480607", "Bulgarian Rose");
        put("480656", "Clairvoyant");
        put("481C1C", "Cocoa Bean");
        put("483131", "Woody Brown");
        put("483C32", "Taupe");
        put("49170C", "Van Cleef");
        put("492615", "Brown Derby");
        put("49371B", "Metallic Bronze");
        put("495400", "Verdun Green");
        put("496679", "Blue Bayoux");
        put("497183", "Bismark");
        put("4A2A04", "Bracken");
        put("4A3004", "Deep Bronze");
        put("4A3C30", "Mondo");
        put("4A4244", "Tundora");
        put("4A444B", "Gravel");
        put("4A4E5A", "Trout");
        put("4B0082", "Pigment Indigo");
        put("4B5D52", "Nandor");
        put("4C3024", "Saddle");
        put("4C4F56", "Abbey");
        put("4D0135", "Blackberry");
        put("4D0A18", "Cab Sav");
        put("4D1E01", "Indian Tan");
        put("4D282D", "Cowboy");
        put("4D282E", "Livid Brown");
        put("4D3833", "Rock");
        put("4D3D14", "Punga");
        put("4D400F", "Bronzetone");
        put("4D5328", "Woodland");
        put("4E0606", "Mahogany");
        put("4E2A5A", "Bossanova");
        put("4E3B41", "Matterhorn");
        put("4E420C", "Bronze Olive");
        put("4E4562", "Mulled Wine");
        put("4E6649", "Axolotl");
        put("4E7F9E", "Wedgewood");
        put("4EABD1", "Shakespeare");
        put("4F1C70", "Honey Flower");
        put("4F2398", "Daisy Bush");
        put("4F69C6", "Indigo");
        put("4F7942", "Fern Green");
        put("4F9D5D", "Fruit Salad");
        put("4FA83D", "Apple");
        put("504351", "Mortar");
        put("507096", "Kashmir Blue");
        put("507672", "Cutty Sark");
        put("50C878", "Emerald");
        put("514649", "Emperor");
        put("516E3D", "Chalet Green");
        put("517C66", "Como");
        put("51808F", "Smalt Blue");
        put("52001F", "Castro");
        put("520C17", "Maroon Oak");
        put("523C94", "Gigas");
        put("533455", "Voodoo");
        put("534491", "Victoria");
        put("53824B", "Hippie Green");
        put("541012", "Heath");
        put("544333", "Judge Gray");
        put("54534D", "Fuscous Gray");
        put("549019", "Vida Loca");
        put("55280C", "Cioccolato");
        put("555B10", "Saratoga");
        put("556D56", "Finlandia");
        put("5590D9", "Havelock Blue");
        put("56B4BE", "Fountain Blue");
        put("578363", "Spring Leaves");
        put("583401", "Saddle Brown");
        put("585562", "Scarpa Flow");
        put("587156", "Cactus");
        put("589AAF", "Hippie Blue");
        put("591D35", "Wine Berry");
        put("592804", "Brown Bramble");
        put("593737", "Congo Brown");
        put("594433", "Millbrook");
        put("5A6E9C", "Waikawa Gray");
        put("5A87A0", "Horizon");
        put("5B3013", "Jambalaya");
        put("5C0120", "Bordeaux");
        put("5C0536", "Mulberry Wood");
        put("5C2E01", "Carnaby Tan");
        put("5C5D75", "Comet");
        put("5D1E0F", "Redwood");
        put("5D4C51", "Don Juan");
        put("5D5C58", "Chicago");
        put("5D5E37", "Verdigris");
        put("5D7747", "Dingley");
        put("5DA19F", "Breaker Bay");
        put("5E483E", "Kabul");
        put("5E5D3B", "Hemlock");
        put("5F3D26", "Irish Coffee");
        put("5F5F6E", "Mid Gray");
        put("5F6672", "Shuttle Gray");
        put("5FA777", "Aqua Forest");
        put("5FB3AC", "Tradewind");
        put("604913", "Horses Neck");
        put("605B73", "Smoky");
        put("606E68", "Corduroy");
        put("6093D1", "Danube");
        put("612718", "Espresso");
        put("614051", "Eggplant");
        put("615D30", "Costa Del Sol");
        put("61845F", "Glade Green");
        put("622F30", "Buccaneer");
        put("623F2D", "Quincy");
        put("624E9A", "Butterfly Bush");
        put("625119", "West Coast");
        put("626649", "Finch");
        put("639A8F", "Patina");
        put("63B76C", "Fern");
        put("6456B7", "Blue Violet");
        put("646077", "Dolphin");
        put("646463", "Storm Dust");
        put("646A54", "Siam");
        put("646E75", "Nevada");
        put("6495ED", "Cornflower Blue");
        put("64CCDB", "Viking");
        put("65000B", "Rosewood");
        put("651A14", "Cherrywood");
        put("652DC1", "Purple Heart");
        put("657220", "Fern Frond");
        put("65745D", "Willow Grove");
        put("65869F", "Hoki");
        put("660045", "Pompadour");
        put("660099", "Purple");
        put("66023C", "Tyrian Purple");
        put("661010", "Dark Tan");
        put("66B58F", "Silver Tree");
        put("66FF00", "Bright Green");
        put("66FF66", "Screamin' Green");
        put("67032D", "Black Rose");
        put("675FA6", "Scampi");
        put("676662", "Ironside Gray");
        put("678975", "Viridian Green");
        put("67A712", "Christi");
        put("683600", "Nutmeg Wood Finish");
        put("685558", "Zambezi");
        put("685E6E", "Salt Box");
        put("692545", "Tawny Port");
        put("692D54", "Finn");
        put("695F62", "Scorpion");
        put("697E9A", "Lynch");
        put("6A442E", "Spice");
        put("6A5D1B", "Himalaya");
        put("6A6051", "Soya Bean");
        put("6B2A14", "Hairy Heath");
        put("6B3FA0", "Royal Purple");
        put("6B4E31", "Shingle Fawn");
        put("6B5755", "Dorado");
        put("6B8BA2", "Bermuda Gray");
        put("6B8E23", "Olive Drab");
        put("6C3082", "Eminence");
        put("6CDAE7", "Turquoise Blue");
        put("6D0101", "Lonestar");
        put("6D5E54", "Pine Cone");
        put("6D6C6C", "Dove Gray");
        put("6D9292", "Juniper");
        put("6D92A1", "Gothic");
        put("6E0902", "Red Oxide");
        put("6E1D14", "Moccaccino");
        put("6E4826", "Pickled Bean");
        put("6E4B26", "Dallas");
        put("6E6D57", "Kokoda");
        put("6E7783", "Pale Sky");
        put("6F440C", "Cafe Royale");
        put("6F6A61", "Flint");
        put("6F8E63", "Highland");
        put("6F9D02", "Limeade");
        put("6FD0C5", "Downy");
        put("701C1C", "Persian Plum");
        put("704214", "Sepia");
        put("704A07", "Antique Bronze");
        put("704F50", "Ferra");
        put("706555", "Coffee");
        put("708090", "Slate Gray");
        put("711A00", "Cedar Wood Finish");
        put("71291D", "Metallic Copper");
        put("714693", "Affair");
        put("714AB2", "Studio");
        put("715D47", "Tobacco Brown");
        put("716338", "Yellow Metal");
        put("716B56", "Peat");
        put("716E10", "Olivetone");
        put("717486", "Storm Gray");
        put("718080", "Sirocco");
        put("71D9E2", "Aquamarine Blue");
        put("72010F", "Venetian Red");
        put("724A2F", "Old Copper");
        put("726D4E", "Go Ben");
        put("727B89", "Raven");
        put("731E8F", "Seance");
        put("734A12", "Raw Umber");
        put("736C9F", "Kimberly");
        put("736D58", "Crocodile");
        put("737829", "Crete");
        put("738678", "Xanadu");
        put("74640D", "Spicy Mustard");
        put("747D63", "Limed Ash");
        put("747D83", "Rolling Stone");
        put("748881", "Blue Smoke");
        put("749378", "Laurel");
        put("74C365", "Mantis");
        put("755A57", "Russett");
        put("7563A8", "Deluge");
        put("76395D", "Cosmic");
        put("7666C6", "Blue Marguerite");
        put("76BD17", "Lima");
        put("76D7EA", "Sky Blue");
        put("770F05", "Dark Burgundy");
        put("771F1F", "Crown of Thorns");
        put("773F1A", "Walnut");
        put("776F61", "Pablo");
        put("778120", "Pacifika");
        put("779E86", "Oxley");
        put("77DD77", "Pastel Green");
        put("780109", "Japanese Maple");
        put("782D19", "Mocha");
        put("782F16", "Peanut");
        put("78866B", "Camouflage Green");
        put("788A25", "Wasabi");
        put("788BBA", "Ship Cove");
        put("78A39C", "Sea Nymph");
        put("795D4C", "Roman Coffee");
        put("796878", "Old Lavender");
        put("796989", "Rum");
        put("796A78", "Fedora");
        put("796D62", "Sandstone");
        put("79DEEC", "Spray");
        put("7A013A", "Siren");
        put("7A58C1", "Fuchsia Blue");
        put("7A7A7A", "Boulder");
        put("7A89B8", "Wild Blue Yonder");
        put("7AC488", "De York");
        put("7B3801", "Red Beech");
        put("7B3F00", "Cinnamon");
        put("7B6608", "Yukon Gold");
        put("7B7874", "Tapa");
        put("7B7C94", "Waterloo ");
        put("7B8265", "Flax Smoke");
        put("7B9F80", "Amulet");
        put("7BA05B", "Asparagus");
        put("7C1C05", "Kenyan Copper");
        put("7C7631", "Pesto");
        put("7C778A", "Topaz");
        put("7C7B7A", "Concord");
        put("7C7B82", "Jumbo");
        put("7C881A", "Trendy Green");
        put("7CA1A6", "Gumbo");
        put("7CB0A1", "Acapulco");
        put("7CB7BB", "Neptune");
        put("7D2C14", "Pueblo");
        put("7DA98D", "Bay Leaf");
        put("7DC8F7", "Malibu");
        put("7DD8C6", "Bermuda");
        put("7E3A15", "Copper Canyon");
        put("7F1734", "Claret");
        put("7F3A02", "Peru Tan");
        put("7F626D", "Falcon");
        put("7F7589", "Mobster");
        put("7F76D3", "Moody Blue");
        put("7FFF00", "Chartreuse");
        put("7FFFD4", "Aquamarine");
        put("800000", "Maroon");
        put("800B47", "Rose Bud Cherry");
        put("801818", "Falu Red");
        put("80341F", "Red Robin");
        put("803790", "Vivid Violet");
        put("80461B", "Russet");
        put("807E79", "Friar Gray");
        put("808000", "Olive");
        put("808080", "Gray");
        put("80B3AE", "Gulf Stream");
        put("80B3C4", "Glacier");
        put("80CCEA", "Seagull");
        put("81422C", "Nutmeg");
        put("816E71", "Spicy Pink");
        put("817377", "Empress");
        put("819885", "Spanish Green");
        put("826F65", "Sand Dune");
        put("828685", "Gunsmoke");
        put("828F72", "Battleship Gray");
        put("831923", "Merlot");
        put("837050", "Shadow");
        put("83AA5D", "Chelsea Cucumber");
        put("83D0C6", "Monte Carlo");
        put("843179", "Plum");
        put("84A0A0", "Granny Smith");
        put("8581D9", "Chetwode Blue");
        put("858470", "Bandicoot");
        put("859FAF", "Bali Hai");
        put("85C4CC", "Half Baked");
        put("860111", "Red Devil");
        put("863C3C", "Lotus");
        put("86483C", "Ironstone");
        put("864D1E", "Bull Shot");
        put("86560A", "Rusty Nail");
        put("868974", "Bitter");
        put("86949F", "Regent Gray");
        put("871550", "Disco");
        put("87756E", "Americano");
        put("877C7B", "Hurricane");
        put("878D91", "Oslo Gray");
        put("87AB39", "Sushi");
        put("885342", "Spicy Mix");
        put("886221", "Kumera");
        put("888387", "Suva Gray");
        put("888D65", "Avocado");
        put("893456", "Camelot");
        put("893843", "Solid Pink");
        put("894367", "Cannon Pink");
        put("897D6D", "Makara");
        put("8A3324", "Burnt Umber");
        put("8A73D6", "True V");
        put("8A8360", "Clay Creek");
        put("8A8389", "Monsoon");
        put("8A8F8A", "Stack");
        put("8AB9F1", "Jordy Blue");
        put("8B00FF", "Electric Violet");
        put("8B0723", "Monarch");
        put("8B6B0B", "Corn Harvest");
        put("8B8470", "Olive Haze");
        put("8B847E", "Schooner");
        put("8B8680", "Natural Gray");
        put("8B9C90", "Mantle");
        put("8B9FEE", "Portage");
        put("8BA690", "Envy");
        put("8BA9A5", "Cascade");
        put("8BE6D8", "Riptide");
        put("8C055E", "Cardinal Pink");
        put("8C472F", "Mule Fawn");
        put("8C5738", "Potters Clay");
        put("8C6495", "Trendy Pink");
        put("8D0226", "Paprika");
        put("8D3D38", "Sanguine Brown");
        put("8D3F3F", "Tosca");
        put("8D7662", "Cement");
        put("8D8974", "Granite Green");
        put("8D90A1", "Manatee");
        put("8DA8CC", "Polo Blue");
        put("8E0000", "Red Berry");
        put("8E4D1E", "Rope");
        put("8E6F70", "Opium");
        put("8E775E", "Domino");
        put("8E8190", "Mamba");
        put("8EABC1", "Nepal");
        put("8F021C", "Pohutukawa");
        put("8F3E33", "El Salva");
        put("8F4B0E", "Korma");
        put("8F8176", "Squirrel");
        put("8FD6B4", "Vista Blue");
        put("900020", "Burgundy");
        put("901E1E", "Old Brick");
        put("907874", "Hemp");
        put("907B71", "Almond Frost");
        put("908D39", "Sycamore");
        put("92000A", "Sangria");
        put("924321", "Cumin");
        put("926F5B", "Beaver");
        put("928573", "Stonewall");
        put("928590", "Venus");
        put("9370DB", "Medium Purple");
        put("93CCEA", "Cornflower");
        put("93DFB8", "Algae Green");
        put("944747", "Copper Rust");
        put("948771", "Arrowtown");
        put("950015", "Scarlett");
        put("956387", "Strikemaster");
        put("959396", "Mountain Mist");
        put("960018", "Carmine");
        put("964B00", "Brown");
        put("967059", "Leather");
        put("9678B6", "Purple Mountain's Majesty");
        put("967BB6", "Lavender Purple");
        put("96A8A1", "Pewter");
        put("96BBAB", "Summer Green");
        put("97605D", "Au Chico");
        put("9771B5", "Wisteria");
        put("97CD2D", "Atlantis");
        put("983D61", "Vin Rouge");
        put("9874D3", "Lilac Bush");
        put("98777B", "Bazaar");
        put("98811B", "Hacienda");
        put("988D77", "Pale Oyster");
        put("98FF98", "Mint Green");
        put("990066", "Fresh Eggplant");
        put("991199", "Violet Eggplant");
        put("991613", "Tamarillo");
        put("991B07", "Totem Pole");
        put("996666", "Copper Rose");
        put("9966CC", "Amethyst");
        put("997A8D", "Mountbatten Pink");
        put("9999CC", "Blue Bell");
        put("9A3820", "Prairie Sand");
        put("9A6E61", "Toast");
        put("9A9577", "Gurkha");
        put("9AB973", "Olivine");
        put("9AC2B8", "Shadow Green");
        put("9B4703", "Oregon");
        put("9B9E8F", "Lemon Grass");
        put("9C3336", "Stiletto");
        put("9D5616", "Hawaiian Tan");
        put("9DACB7", "Gull Gray");
        put("9DC209", "Pistachio");
        put("9DE093", "Granny Smith Apple");
        put("9DE5FF", "Anakiwa");
        put("9E5302", "Chelsea Gem");
        put("9E5B40", "Sepia Skin");
        put("9EA587", "Sage");
        put("9EA91F", "Citron");
        put("9EB1CD", "Rock Blue");
        put("9EDEE0", "Morning Glory");
        put("9F381D", "Cognac");
        put("9F821C", "Reef Gold");
        put("9F9F9C", "Star Dust");
        put("9FA0B1", "Santas Gray");
        put("9FD7D3", "Sinbad");
        put("9FDD8C", "Feijoa");
        put("A02712", "Tabasco");
        put("A1750D", "Buttered Rum");
        put("A1ADB5", "Hit Gray");
        put("A1C50A", "Citrus");
        put("A1DAD7", "Aqua Island");
        put("A1E9DE", "Water Leaf");
        put("A2006D", "Flirt");
        put("A23B6C", "Rouge");
        put("A26645", "Cape Palliser");
        put("A2AAB3", "Gray Chateau");
        put("A2AEAB", "Edward");
        put("A3807B", "Pharlap");
        put("A397B4", "Amethyst Smoke");
        put("A3E3ED", "Blizzard Blue");
        put("A4A49D", "Delta");
        put("A4A6D3", "Wistful");
        put("A4AF6E", "Green Smoke");
        put("A50B5E", "Jazzberry Jam");
        put("A59B91", "Zorba");
        put("A5CB0C", "Bahia");
        put("A62F20", "Roof Terracotta");
        put("A65529", "Paarl");
        put("A68B5B", "Barley Corn");
        put("A69279", "Donkey Brown");
        put("A6A29A", "Dawn");
        put("A72525", "Mexican Red");
        put("A7882C", "Luxor Gold");
        put("A85307", "Rich Gold");
        put("A86515", "Reno Sand");
        put("A86B6B", "Coral Tree");
        put("A8989B", "Dusty Gray");
        put("A899E6", "Dull Lavender");
        put("A8A589", "Tallow");
        put("A8AE9C", "Bud");
        put("A8AF8E", "Locust");
        put("A8BD9F", "Norway");
        put("A8E3BD", "Chinook");
        put("A9A491", "Gray Olive");
        put("A9ACB6", "Aluminium");
        put("A9B2C3", "Cadet Blue");
        put("A9B497", "Schist");
        put("A9BDBF", "Tower Gray");
        put("A9BEF2", "Perano");
        put("A9C6C2", "Opal");
        put("AA375A", "Night Shadz");
        put("AA4203", "Fire");
        put("AA8B5B", "Muesli");
        put("AA8D6F", "Sandal");
        put("AAA5A9", "Shady Lady");
        put("AAA9CD", "Logan");
        put("AAABB7", "Spun Pearl");
        put("AAD6E6", "Regent St Blue");
        put("AAF0D1", "Magic Mint");
        put("AB0563", "Lipstick");
        put("AB3472", "Royal Heath");
        put("AB917A", "Sandrift");
        put("ABA0D9", "Cold Purple");
        put("ABA196", "Bronco");
        put("AC8A56", "Limed Oak");
        put("AC91CE", "East Side");
        put("AC9E22", "Lemon Ginger");
        put("ACA494", "Napa");
        put("ACA586", "Hillary");
        put("ACA59F", "Cloudy");
        put("ACACAC", "Silver Chalice");
        put("ACB78E", "Swamp Green");
        put("ACCBB1", "Spring Rain");
        put("ACDD4D", "Conifer");
        put("ACE1AF", "Celadon");
        put("AD781B", "Mandalay");
        put("ADBED1", "Casper");
        put("ADDFAD", "Moss Green");
        put("ADE6C4", "Padua");
        put("ADFF2F", "Green Yellow");
        put("AE4560", "Hippie Pink");
        put("AE6020", "Desert");
        put("AE809E", "Bouquet");
        put("AF4035", "Medium Carmine");
        put("AF4D43", "Apple Blossom");
        put("AF593E", "Brown Rust");
        put("AF8751", "Driftwood");
        put("AF8F2C", "Alpine");
        put("AF9F1C", "Lucky");
        put("AFA09E", "Martini");
        put("AFB1B8", "Bombay");
        put("AFBDD9", "Pigeon Post");
        put("B04C6A", "Cadillac");
        put("B05D54", "Matrix");
        put("B05E81", "Tapestry");
        put("B06608", "Mai Tai");
        put("B09A95", "Del Rio");
        put("B0E0E6", "Powder Blue");
        put("B0E313", "Inch Worm");
        put("B10000", "Bright Red");
        put("B14A0B", "Vesuvius");
        put("B1610B", "Pumpkin Skin");
        put("B16D52", "Santa Fe");
        put("B19461", "Teak");
        put("B1E2C1", "Fringy Flower");
        put("B1F4E7", "Ice Cold");
        put("B20931", "Shiraz");
        put("B2A1EA", "Biloba Flower");
        put("B32D29", "Tall Poppy");
        put("B35213", "Fiery Orange");
        put("B38007", "Hot Toddy");
        put("B3AF95", "Taupe Gray");
        put("B3C110", "La Rioja");
        put("B43332", "Well Read");
        put("B44668", "Blush");
        put("B4CFD3", "Jungle Mist");
        put("B57281", "Turkish Rose");
        put("B57EDC", "Lavender");
        put("B5A27F", "Mongoose");
        put("B5B35C", "Olive Green");
        put("B5D2CE", "Jet Stream");
        put("B5ECDF", "Cruise");
        put("B6316C", "Hibiscus");
        put("B69D98", "Thatch");
        put("B6B095", "Heathered Gray");
        put("B6BAA4", "Eagle");
        put("B6D1EA", "Spindle");
        put("B6D3BF", "Gum Leaf");
        put("B7410E", "Rust");
        put("B78E5C", "Muddy Waters");
        put("B7A214", "Sahara");
        put("B7A458", "Husk");
        put("B7B1B1", "Nobel");
        put("B7C3D0", "Heather");
        put("B7F0BE", "Madang");
        put("B81104", "Milano Red");
        put("B87333", "Copper");
        put("B8B56A", "Gimblet");
        put("B8C1B1", "Green Spring");
        put("B8C25D", "Celery");
        put("B8E0F9", "Sail");
        put("B94E48", "Chestnut");
        put("B95140", "Crail");
        put("B98D28", "Marigold");
        put("B9C46A", "Wild Willow");
        put("B9C8AC", "Rainee");
        put("BA0101", "Guardsman Red");
        put("BA450C", "Rock Spray");
        put("BA6F1E", "Bourbon");
        put("BA7F03", "Pirate Gold");
        put("BAB1A2", "Nomad");
        put("BAC7C9", "Submarine");
        put("BAEEF9", "Charlotte");
        put("BB3385", "Medium Red Violet");
        put("BB8983", "Brandy Rose");
        put("BBD009", "Rio Grande");
        put("BBD7C1", "Surf");
        put("BCC9C2", "Powder Ash");
        put("BD5E2E", "Tuscany");
        put("BD978E", "Quicksand");
        put("BDB1A8", "Silk");
        put("BDB2A1", "Malta");
        put("BDB3C7", "Chatelle");
        put("BDBBD7", "Lavender Gray");
        put("BDBDC6", "French Gray");
        put("BDC8B3", "Clay Ash");
        put("BDC9CE", "Loblolly");
        put("BDEDFD", "French Pass");
        put("BEA6C3", "London Hue");
        put("BEB5B7", "Pink Swan");
        put("BEDE0D", "Fuego");
        put("BF5500", "Rose of Sharon");
        put("BFB8B0", "Tide");
        put("BFBED8", "Blue Haze");
        put("BFC1C2", "Silver Sand");
        put("BFC921", "Key Lime Pie");
        put("BFDBE2", "Ziggurat");
        put("BFFF00", "Lime");
        put("C02B18", "Thunderbird");
        put("C04737", "Mojo");
        put("C08081", "Old Rose");
        put("C0C0C0", "Silver");
        put("C0D3B9", "Pale Leaf");
        put("C0D8B6", "Pixie Green");
        put("C1440E", "Tia Maria");
        put("C154C1", "Fuchsia Pink");
        put("C1A004", "Buddha Gold");
        put("C1B7A4", "Bison Hide");
        put("C1BAB0", "Tea");
        put("C1BECD", "Gray Suit");
        put("C1D7B0", "Sprout");
        put("C1F07C", "Sulu");
        put("C26B03", "Indochine");
        put("C2955D", "Twine");
        put("C2BDB6", "Cotton Seed");
        put("C2CAC4", "Pumice");
        put("C2E8E5", "Jagged Ice");
        put("C32148", "Maroon Flush");
        put("C3B091", "Indian Khaki");
        put("C3BFC1", "Pale Slate");
        put("C3C3BD", "Gray Nickel");
        put("C3CDE6", "Periwinkle Gray");
        put("C3D1D1", "Tiara");
        put("C3DDF9", "Tropical Blue");
        put("C41E3A", "Cardinal");
        put("C45655", "Fuzzy Wuzzy Brown");
        put("C45719", "Orange Roughy");
        put("C4C4BC", "Mist Gray");
        put("C4D0B0", "Coriander");
        put("C4F4EB", "Mint Tulip");
        put("C54B8C", "Mulberry");
        put("C59922", "Nugget");
        put("C5994B", "Tussock");
        put("C5DBCA", "Sea Mist");
        put("C5E17A", "Yellow Green");
        put("C62D42", "Brick Red");
        put("C6726B", "Contessa");
        put("C69191", "Oriental Pink");
        put("C6A84B", "Roti");
        put("C6C3B5", "Ash");
        put("C6C8BD", "Kangaroo");
        put("C6E610", "Las Palmas");
        put("C7031E", "Monza");
        put("C71585", "Red Violet");
        put("C7BCA2", "Coral Reef");
        put("C7C1FF", "Melrose");
        put("C7C4BF", "Cloud");
        put("C7C9D5", "Ghost");
        put("C7CD90", "Pine Glade");
        put("C7DDE5", "Botticelli");
        put("C88A65", "Antique Brass");
        put("C8A2C8", "Lilac");
        put("C8A528", "Hokey Pokey");
        put("C8AABF", "Lily");
        put("C8B568", "Laser");
        put("C8E3D7", "Edgewater");
        put("C96323", "Piper");
        put("C99415", "Pizza");
        put("C9A0DC", "Light Wisteria");
        put("C9B29B", "Rodeo Dust");
        put("C9B35B", "Sundance");
        put("C9B93B", "Earls Green");
        put("C9C0BB", "Silver Rust");
        put("C9D9D2", "Conch");
        put("C9FFA2", "Reef");
        put("C9FFE5", "Aero Blue");
        put("CA3435", "Flush Mahogany");
        put("CABB48", "Turmeric");
        put("CADCD4", "Paris White");
        put("CAE00D", "Bitter Lemon");
        put("CAE6DA", "Skeptic");
        put("CB8FA9", "Viola");
        put("CBCAB6", "Foggy Gray");
        put("CBD3B0", "Green Mist");
        put("CBDBD6", "Nebula");
        put("CC3333", "Persian Red");
        put("CC5500", "Burnt Orange");
        put("CC7722", "Ochre");
        put("CC8899", "Puce");
        put("CCCAA8", "Thistle Green");
        put("CCCCFF", "Periwinkle");
        put("CCFF00", "Electric Lime");
        put("CD5700", "Tenn");
        put("CD5C5C", "Chestnut Rose");
        put("CD8429", "Brandy Punch");
        put("CDF4FF", "Onahau");
        put("CEB98F", "Sorrell Brown");
        put("CEBABA", "Cold Turkey");
        put("CEC291", "Yuma");
        put("CEC7A7", "Chino");
        put("CFA39D", "Eunry");
        put("CFB53B", "Old Gold");
        put("CFDCCF", "Tasman");
        put("CFE5D2", "Surf Crest");
        put("CFF9F3", "Humming Bird");
        put("CFFAF4", "Scandal");
        put("D05F04", "Red Stage");
        put("D06DA1", "Hopbush");
        put("D07D12", "Meteor");
        put("D0BEF8", "Perfume");
        put("D0C0E5", "Prelude");
        put("D0F0C0", "Tea Green");
        put("D18F1B", "Geebung");
        put("D1BEA8", "Vanilla");
        put("D1C6B4", "Soft Amber");
        put("D1D2CA", "Celeste");
        put("D1D2DD", "Mischka");
        put("D1E231", "Pear");
        put("D2691E", "Hot Cinnamon");
        put("D27D46", "Raw Sienna");
        put("D29EAA", "Careys Pink");
        put("D2B48C", "Tan");
        put("D2DA97", "Deco");
        put("D2F6DE", "Blue Romance");
        put("D2F8B0", "Gossip");
        put("D3CBBA", "Sisal");
        put("D3CDC5", "Swirl");
        put("D47494", "Charm");
        put("D4B6AF", "Clam Shell");
        put("D4BF8D", "Straw");
        put("D4C4A8", "Akaroa");
        put("D4CD16", "Bird Flower");
        put("D4D7D9", "Iron");
        put("D4DFE2", "Geyser");
        put("D4E2FC", "Hawkes Blue");
        put("D54600", "Grenadier");
        put("D591A4", "Can Can");
        put("D59A6F", "Whiskey");
        put("D5D195", "Winter Hazel");
        put("D5F6E3", "Granny Apple");
        put("D69188", "My Pink");
        put("D6C562", "Tacha");
        put("D6CEF6", "Moon Raker");
        put("D6D6D1", "Quill Gray");
        put("D6FFDB", "Snowy Mint");
        put("D7837F", "New York Pink");
        put("D7C498", "Pavlova");
        put("D7D0FF", "Fog");
        put("D84437", "Valencia");
        put("D87C63", "Japonica");
        put("D8BFD8", "Thistle");
        put("D8C2D5", "Maverick");
        put("D8FCFA", "Foam");
        put("D94972", "Cabaret");
        put("D99376", "Burning Sand");
        put("D9B99B", "Cameo");
        put("D9D6CF", "Timberwolf");
        put("D9DCC1", "Tana");
        put("D9E4F5", "Link Water");
        put("D9F7FF", "Mabel");
        put("DA3287", "Cerise");
        put("DA5B38", "Flame Pea");
        put("DA6304", "Bamboo");
        put("DA6A41", "Red Damask");
        put("DA70D6", "Orchid");
        put("DA8A67", "Copperfield");
        put("DAA520", "Golden Grass");
        put("DAECD6", "Zanah");
        put("DAF4F0", "Iceberg");
        put("DAFAFF", "Oyster Bay");
        put("DB5079", "Cranberry");
        put("DB9690", "Petite Orchid");
        put("DB995E", "Di Serria");
        put("DBDBDB", "Alto");
        put("DBFFF8", "Frosted Mint");
        put("DC143C", "Crimson");
        put("DC4333", "Punch");
        put("DCB20C", "Galliano");
        put("DCB4BC", "Blossom");
        put("DCD747", "Wattle");
        put("DCD9D2", "Westar");
        put("DCDDCC", "Moon Mist");
        put("DCEDB4", "Caper");
        put("DCF0EA", "Swans Down");
        put("DDD6D5", "Swiss Coffee");
        put("DDF9F1", "White Ice");
        put("DE3163", "Cerise Red");
        put("DE6360", "Roman");
        put("DEA681", "Tumbleweed");
        put("DEBA13", "Gold Tips");
        put("DEC196", "Brandy");
        put("DECBC6", "Wafer");
        put("DED4A4", "Sapling");
        put("DED717", "Barberry");
        put("DEE5C0", "Beryl Green");
        put("DEF5FF", "Pattens Blue");
        put("DF73FF", "Heliotrope");
        put("DFBE6F", "Apache");
        put("DFCD6F", "Chenin");
        put("DFCFDB", "Lola");
        put("DFECDA", "Willow Brook");
        put("DFFF00", "Chartreuse Yellow");
        put("E0B0FF", "Mauve");
        put("E0B646", "Anzac");
        put("E0B974", "Harvest Gold");
        put("E0C095", "Calico");
        put("E0FFFF", "Baby Blue");
        put("E16865", "Sunglo");
        put("E1BC64", "Equator");
        put("E1C0C8", "Pink Flare");
        put("E1E6D6", "Periglacial Blue");
        put("E1EAD4", "Kidnapper");
        put("E1F6E8", "Tara");
        put("E25465", "Mandy");
        put("E2725B", "Terracotta");
        put("E28913", "Golden Bell");
        put("E292C0", "Shocking");
        put("E29418", "Dixie");
        put("E29CD2", "Light Orchid");
        put("E2D8ED", "Snuff");
        put("E2EBED", "Mystic");
        put("E2F3EC", "Apple Green");
        put("E30B5C", "Razzmatazz");
        put("E32636", "Alizarin Crimson");
        put("E34234", "Cinnabar");
        put("E3BEBE", "Cavern Pink");
        put("E3F5E1", "Peppermint");
        put("E3F988", "Mindaro");
        put("E47698", "Deep Blush");
        put("E49B0F", "Gamboge");
        put("E4C2D5", "Melanie");
        put("E4CFDE", "Twilight");
        put("E4D1C0", "Bone");
        put("E4D422", "Sunflower");
        put("E4D5B7", "Grain Brown");
        put("E4D69B", "Zombie");
        put("E4F6E7", "Frostee");
        put("E4FFD1", "Snow Flurry");
        put("E52B50", "Amaranth");
        put("E5841B", "Zest");
        put("E5CCC9", "Dust Storm");
        put("E5D7BD", "Stark White");
        put("E5D8AF", "Hampton");
        put("E5E0E1", "Bon Jour");
        put("E5E5E5", "Mercury");
        put("E5F9F6", "Polar");
        put("E64E03", "Trinidad");
        put("E6BE8A", "Gold Sand");
        put("E6BEA5", "Cashmere");
        put("E6D7B9", "Double Spanish White");
        put("E6E4D4", "Satin Linen");
        put("E6F2EA", "Harp");
        put("E6F8F3", "Off Green");
        put("E6FFE9", "Hint of Green");
        put("E6FFFF", "Tranquil");
        put("E77200", "Mango Tango");
        put("E7730A", "Christine");
        put("E79F8C", "Tonys Pink");
        put("E79FC4", "Kobi");
        put("E7BCB4", "Rose Fog");
        put("E7BF05", "Corn");
        put("E7CD8C", "Putty");
        put("E7ECE6", "Gray Nurse");
        put("E7F8FF", "Lily White");
        put("E7FEFF", "Bubbles");
        put("E89928", "Fire Bush");
        put("E8B9B3", "Shilo");
        put("E8E0D5", "Pearl Bush");
        put("E8EBE0", "Green White");
        put("E8F1D4", "Chrome White");
        put("E8F2EB", "Gin");
        put("E8F5F2", "Aqua Squeeze");
        put("E96E00", "Clementine");
        put("E97451", "Burnt Sienna");
        put("E97C07", "Tahiti Gold");
        put("E9CECD", "Oyster Pink");
        put("E9D75A", "Confetti");
        put("E9E3E3", "Ebb");
        put("E9F8ED", "Ottoman");
        put("E9FFFD", "Clear Day");
        put("EA88A8", "Carissma");
        put("EAAE69", "Porsche");
        put("EAB33B", "Tulip Tree");
        put("EAC674", "Rob Roy");
        put("EADAB8", "Raffia");
        put("EAE8D4", "White Rock");
        put("EAF6EE", "Panache");
        put("EAF6FF", "Solitude");
        put("EAF9F5", "Aqua Spring");
        put("EAFFFE", "Dew");
        put("EB9373", "Apricot");
        put("EBC2AF", "Zinnwaldite");
        put("ECA927", "Fuel Yellow");
        put("ECC54E", "Ronchi");
        put("ECC7EE", "French Lilac");
        put("ECCDB9", "Just Right");
        put("ECE090", "Wild Rice");
        put("ECEBBD", "Fall Green");
        put("ECEBCE", "Aths Special");
        put("ECF245", "Starship");
        put("ED0A3F", "Red Ribbon");
        put("ED7A1C", "Tango");
        put("ED9121", "Carrot Orange");
        put("ED989E", "Sea Pink");
        put("EDB381", "Tacao");
        put("EDC9AF", "Desert Sand");
        put("EDCDAB", "Pancho");
        put("EDDCB1", "Chamois");
        put("EDEA99", "Primrose");
        put("EDF5DD", "Frost");
        put("EDF5F5", "Aqua Haze");
        put("EDF6FF", "Zumthor");
        put("EDF9F1", "Narvik");
        put("EDFC84", "Honeysuckle");
        put("EE82EE", "Lavender Magenta");
        put("EEC1BE", "Beauty Bush");
        put("EED794", "Chalky");
        put("EED9C4", "Almond");
        put("EEDC82", "Flax");
        put("EEDEDA", "Bizarre");
        put("EEE3AD", "Double Colonial White");
        put("EEEEE8", "Cararra");
        put("EEEF78", "Manz");
        put("EEF0C8", "Tahuna Sands");
        put("EEF0F3", "Athens Gray");
        put("EEF3C3", "Tusk");
        put("EEF4DE", "Loafer");
        put("EEF6F7", "Catskill White");
        put("EEFDFF", "Twilight Blue");
        put("EEFF9A", "Jonquil");
        put("EEFFE2", "Rice Flower");
        put("EF863F", "Jaffa");
        put("EFEFEF", "Gallery");
        put("EFF2F3", "Porcelain");
        put("F091A9", "Mauvelous");
        put("F0D52D", "Golden Dream");
        put("F0DB7D", "Golden Sand");
        put("F0DC82", "Buff");
        put("F0E2EC", "Prim");
        put("F0E68C", "Khaki");
        put("F0EEFD", "Selago");
        put("F0EEFF", "Titan White");
        put("F0F8FF", "Alice Blue");
        put("F0FCEA", "Feta");
        put("F18200", "Gold Drop");
        put("F19BAB", "Wewak");
        put("F1E788", "Sahara Sand");
        put("F1E9D2", "Parchment");
        put("F1E9FF", "Blue Chalk");
        put("F1EEC1", "Mint Julep");
        put("F1F1F1", "Seashell");
        put("F1F7F2", "Saltpan");
        put("F1FFAD", "Tidal");
        put("F1FFC8", "Chiffon");
        put("F2552A", "Flamingo");
        put("F28500", "Tangerine");
        put("F2C3B2", "Mandys Pink");
        put("F2F2F2", "Concrete");
        put("F2FAFA", "Black Squeeze");
        put("F34723", "Pomegranate");
        put("F3AD16", "Buttercup");
        put("F3D69D", "New Orleans");
        put("F3D9DF", "Vanilla Ice");
        put("F3E7BB", "Sidecar");
        put("F3E9E5", "Dawn Pink");
        put("F3EDCF", "Wheatfield");
        put("F3FB62", "Canary");
        put("F3FBD4", "Orinoco");
        put("F3FFD8", "Carla");
        put("F400A1", "Hollywood Cerise");
        put("F4A460", "Sandy brown");
        put("F4C430", "Saffron");
        put("F4D81C", "Ripe Lemon");
        put("F4EBD3", "Janna");
        put("F4F2EE", "Pampas");
        put("F4F4F4", "Wild Sand");
        put("F4F8FF", "Zircon");
        put("F57584", "Froly");
        put("F5C85C", "Cream Can");
        put("F5C999", "Manhattan");
        put("F5D5A0", "Maize");
        put("F5DEB3", "Wheat");
        put("F5E7A2", "Sandwisp");
        put("F5E7E2", "Pot Pourri");
        put("F5E9D3", "Albescent White");
        put("F5EDEF", "Soft Peach");
        put("F5F3E5", "Ecru White");
        put("F5F5DC", "Beige");
        put("F5FB3D", "Golden Fizz");
        put("F5FFBE", "Australian Mint");
        put("F64A8A", "French Rose");
        put("F653A6", "Brilliant Rose");
        put("F6A4C9", "Illusion");
        put("F6F0E6", "Merino");
        put("F6F7F7", "Black Haze");
        put("F6FFDC", "Spring Sun");
        put("F7468A", "Violet Red");
        put("F77703", "Chilean Fire");
        put("F77FBE", "Persian Pink");
        put("F7B668", "Rajah");
        put("F7C8DA", "Azalea");
        put("F7DBE6", "We Peep");
        put("F7F2E1", "Quarter Spanish White");
        put("F7F5FA", "Whisper");
        put("F7FAF7", "Snow Drift");
        put("F8B853", "Casablanca");
        put("F8C3DF", "Chantilly");
        put("F8D9E9", "Cherub");
        put("F8DB9D", "Marzipan");
        put("F8DD5C", "Energy Yellow");
        put("F8E4BF", "Givry");
        put("F8F0E8", "White Linen");
        put("F8F4FF", "Magnolia");
        put("F8F6F1", "Spring Wood");
        put("F8F7DC", "Coconut Cream");
        put("F8F7FC", "White Lilac");
        put("F8F8F7", "Desert Storm");
        put("F8F99C", "Texas");
        put("F8FACD", "Corn Field");
        put("F8FDD3", "Mimosa");
        put("F95A61", "Carnation");
        put("F9BF58", "Saffron Mango");
        put("F9E0ED", "Carousel Pink");
        put("F9E4BC", "Dairy Cream");
        put("F9E663", "Portica");
        put("F9EAF3", "Amour");
        put("F9F8E4", "Rum Swizzle");
        put("F9FF8B", "Dolly");
        put("F9FFF6", "Sugar Cane");
        put("FA7814", "Ecstasy");
        put("FA9D5A", "Tan Hide");
        put("FAD3A2", "Corvette");
        put("FADFAD", "Peach Yellow");
        put("FAE600", "Turbo");
        put("FAEAB9", "Astra");
        put("FAECCC", "Champagne");
        put("FAF0E6", "Linen");
        put("FAF3F0", "Fantasy");
        put("FAF7D6", "Citrine White");
        put("FAFAFA", "Alabaster");
        put("FAFDE4", "Hint of Yellow");
        put("FAFFA4", "Milan");
        put("FB607F", "Brink Pink");
        put("FB8989", "Geraldine");
        put("FBA0E3", "Lavender Rose");
        put("FBA129", "Sea Buckthorn");
        put("FBAC13", "Sun");
        put("FBAED2", "Lavender Pink");
        put("FBB2A3", "Rose Bud");
        put("FBBEDA", "Cupid");
        put("FBCCE7", "Classic Rose");
        put("FBCEB1", "Apricot Peach");
        put("FBE7B2", "Banana Mania");
        put("FBE870", "Marigold Yellow");
        put("FBE96C", "Festival");
        put("FBEA8C", "Sweet Corn");
        put("FBEC5D", "Candy Corn");
        put("FBF9F9", "Hint of Red");
        put("FBFFBA", "Shalimar");
        put("FC0FC0", "Shocking Pink");
        put("FC80A5", "Tickle Me Pink");
        put("FC9C1D", "Tree Poppy");
        put("FCC01E", "Lightning Yellow");
        put("FCD667", "Goldenrod");
        put("FCD917", "Candlelight");
        put("FCDA98", "Cherokee");
        put("FCF4D0", "Double Pearl Lusta");
        put("FCF4DC", "Pearl Lusta");
        put("FCF8F7", "Vista White");
        put("FCFBF3", "Bianca");
        put("FCFEDA", "Moon Glow");
        put("FCFFE7", "China Ivory");
        put("FCFFF9", "Ceramic");
        put("FD0E35", "Torch Red");
        put("FD5B78", "Wild Watermelon");
        put("FD7B33", "Crusta");
        put("FD7C07", "Sorbus");
        put("FD9FA2", "Sweet Pink");
        put("FDD5B1", "Light Apricot");
        put("FDD7E4", "Pig Pink");
        put("FDE1DC", "Cinderella");
        put("FDE295", "Golden Glow");
        put("FDE910", "Lemon");
        put("FDF5E6", "Old Lace");
        put("FDF6D3", "Half Colonial White");
        put("FDF7AD", "Drover");
        put("FDFEB8", "Pale Prim");
        put("FDFFD5", "Cumulus");
        put("FE28A2", "Persian Rose");
        put("FE4C40", "Sunset Orange");
        put("FE6F5E", "Bittersweet");
        put("FE9D04", "California");
        put("FEA904", "Yellow Sea");
        put("FEBAAD", "Melon");
        put("FED33C", "Bright Sun");
        put("FED85D", "Dandelion");
        put("FEDB8D", "Salomie");
        put("FEE5AC", "Cape Honey");
        put("FEEBF3", "Remy");
        put("FEEFCE", "Oasis");
        put("FEF0EC", "Bridesmaid");
        put("FEF2C7", "Beeswax");
        put("FEF3D8", "Bleach White");
        put("FEF4CC", "Pipi");
        put("FEF4DB", "Half Spanish White");
        put("FEF4F8", "Wisp Pink");
        put("FEF5F1", "Provincial Pink");
        put("FEF7DE", "Half Dutch White");
        put("FEF8E2", "Solitaire");
        put("FEF8FF", "White Pointer");
        put("FEF9E3", "Off Yellow");
        put("FEFCED", "Orange White");
        put("FF0000", "Red");
        put("FF007F", "Rose");
        put("FF00CC", "Purple Pizzazz");
        put("FF00FF", "Magenta");
        put("FF2400", "Scarlet");
        put("FF3399", "Wild Strawberry");
        put("FF33CC", "Razzle Dazzle Rose");
        put("FF355E", "Radical Red");
        put("FF3F34", "Red Orange");
        put("FF4040", "Coral Red");
        put("FF4D00", "Vermilion");
        put("FF4F00", "International Orange");
        put("FF6037", "Outrageous Orange");
        put("FF6600", "Blaze Orange");
        put("FF66FF", "Pink Flamingo");
        put("FF681F", "Orange");
        put("FF69B4", "Hot Pink");
        put("FF6B53", "Persimmon");
        put("FF6FFF", "Blush Pink");
        put("FF7034", "Burning Orange");
        put("FF7518", "Pumpkin");
        put("FF7D07", "Flamenco");
        put("FF7F00", "Flush Orange");
        put("FF7F50", "Coral");
        put("FF8C69", "Salmon");
        put("FF9000", "Pizazz");
        put("FF910F", "West Side");
        put("FF91A4", "Pink Salmon");
        put("FF9933", "Neon Carrot");
        put("FF9966", "Atomic Tangerine");
        put("FF9980", "Vivid Tangerine");
        put("FF9E2C", "Sunshade");
        put("FFA000", "Orange Peel");
        put("FFA194", "Mona Lisa");
        put("FFA500", "Web Orange");
        put("FFA6C9", "Carnation Pink");
        put("FFAB81", "Hit Pink");
        put("FFAE42", "Yellow Orange");
        put("FFB0AC", "Cornflower Lilac");
        put("FFB1B3", "Sundown");
        put("FFB31F", "My Sin");
        put("FFB555", "Texas Rose");
        put("FFB7D5", "Cotton Candy");
        put("FFB97B", "Macaroni and Cheese");
        put("FFBA00", "Selective Yellow");
        put("FFBD5F", "Koromiko");
        put("FFBF00", "Amber");
        put("FFC0A8", "Wax Flower");
        put("FFC0CB", "Pink");
        put("FFC3C0", "Your Pink");
        put("FFC901", "Supernova");
        put("FFCBA4", "Flesh");
        put("FFCC33", "Sunglow");
        put("FFCC5C", "Golden Tainoi");
        put("FFCC99", "Peach Orange");
        put("FFCD8C", "Chardonnay");
        put("FFD1DC", "Pastel Pink");
        put("FFD2B7", "Romantic");
        put("FFD38C", "Grandis");
        put("FFD700", "Gold");
        put("FFD800", "School bus Yellow");
        put("FFD8D9", "Cosmos");
        put("FFDB58", "Mustard");
        put("FFDCD6", "Peach Schnapps");
        put("FFDDAF", "Caramel");
        put("FFDDCD", "Tuft Bush");
        put("FFDDCF", "Watusi");
        put("FFDDF4", "Pink Lace");
        put("FFDEAD", "Navajo White");
        put("FFDEB3", "Frangipani");
        put("FFE1DF", "Pippin");
        put("FFE1F2", "Pale Rose");
        put("FFE2C5", "Negroni");
        put("FFE5A0", "Cream Brulee");
        put("FFE5B4", "Peach");
        put("FFE6C7", "Tequila");
        put("FFE772", "Kournikova");
        put("FFEAC8", "Sandy Beach");
        put("FFEAD4", "Karry");
        put("FFEC13", "Broom");
        put("FFEDBC", "Colonial White");
        put("FFEED8", "Derby");
        put("FFEFA1", "Vis Vis");
        put("FFEFC1", "Egg White");
        put("FFEFD5", "Papaya Whip");
        put("FFEFEC", "Fair Pink");
        put("FFF0DB", "Peach Cream");
        put("FFF0F5", "Lavender blush");
        put("FFF14F", "Gorse");
        put("FFF1B5", "Buttermilk");
        put("FFF1D8", "Pink Lady");
        put("FFF1EE", "Forget Me Not");
        put("FFF1F9", "Tutu");
        put("FFF39D", "Picasso");
        put("FFF3F1", "Chardon");
        put("FFF46E", "Paris Daisy");
        put("FFF4CE", "Barley White");
        put("FFF4DD", "Egg Sour");
        put("FFF4E0", "Sazerac");
        put("FFF4E8", "Serenade");
        put("FFF4F3", "Chablis");
        put("FFF5EE", "Seashell Peach");
        put("FFF5F3", "Sauvignon");
        put("FFF6D4", "Milk Punch");
        put("FFF6DF", "Varden");
        put("FFF6F5", "Rose White");
        put("FFF8D1", "Baja White");
        put("FFF9E2", "Gin Fizz");
        put("FFF9E6", "Early Dawn");
        put("FFFACD", "Lemon Chiffon");
        put("FFFAF4", "Bridal Heath");
        put("FFFBDC", "Scotch Mist");
        put("FFFBF9", "Soapstone");
        put("FFFC99", "Witch Haze");
        put("FFFCEA", "Buttery White");
        put("FFFCEE", "Island Spice");
        put("FFFDD0", "Cream");
        put("FFFDE6", "Chilean Heath");
        put("FFFDE8", "Travertine");
        put("FFFDF3", "Orchid White");
        put("FFFDF4", "Quarter Pearl Lusta");
        put("FFFEE1", "Half and Half");
        put("FFFEEC", "Apricot White");
        put("FFFEF0", "Rice Cake");
        put("FFFEF6", "Black White");
        put("FFFEFD", "Romance");
        put("FFFF00", "Yellow");
        put("FFFF66", "Laser Lemon");
        put("FFFF99", "Pale Canary");
        put("FFFFB4", "Portafino");
        put("FFFFF0", "Ivory");
        put("FFFFFF", "White");
    }};

    private final static Map<String, ColorHolder> COLOR_MAP = new HashMap<String, ColorHolder>(){{
        Set<String> colorHexes = NAMES.keySet();
        for (String colorHex : colorHexes) {
            put(colorHex, new ColorHolder(colorHex, NAMES.get(colorHex)));
        }
    }};
}
